# Generated by Django 2.2.4 on 2020-02-03 03:01

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businessGroup', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('baseclass_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='businessGroup.BaseClass')),
                ('answer_data', jsonfield.fields.JSONField(blank=True, null=True)),
                ('submit', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('inprogress', 'inprogress'), ('completed', 'completed'), ('reviewing', 'reviewing'), ('reviewed', 'reviewed')], default='inactive', max_length=20)),
                ('attendance_update', models.BooleanField(default=True)),
                ('total_score', models.DecimalField(blank=True, decimal_places=2, default='0', max_digits=5, null=True)),
            ],
            bases=('businessGroup.baseclass',),
        ),
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('baseclass_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='businessGroup.BaseClass')),
                ('assessment_name', models.CharField(max_length=20, null=True, unique=True)),
                ('as_type', models.CharField(choices=[('objective', 'objective'), ('descriptive', 'descriptive'), ('observation', 'observation'), ('attendance', 'attendance')], max_length=20)),
            ],
            bases=('businessGroup.baseclass',),
        ),
        migrations.CreateModel(
            name='MultipartData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='BatchAssessment',
            fields=[
                ('baseclass_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='businessGroup.BaseClass')),
                ('assessment_data', jsonfield.fields.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('INITIATED', 'initiated'), ('APPROVED', 'approved'), ('PENDING', 'pending'), ('NOT APPROVED', 'not approved')], default='INITIATED', max_length=12)),
                ('duration', models.DurationField(blank=True, null=True)),
                ('scheduled_at', models.DateField(blank=True, null=True)),
                ('end_at', models.DateField(blank=True, null=True)),
                ('active', models.BooleanField(default=False)),
                ('assmt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assessment', to='assessment.Assessment')),
                ('batches', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='batch', to='businessGroup.Batch')),
            ],
            bases=('businessGroup.baseclass',),
        ),
    ]
