# Generated by Django 2.2.4 on 2020-06-28 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0003_auto_20200402_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='as_type',
            field=models.CharField(choices=[('objective', 'objective'), ('descriptive', 'descriptive'), ('observation', 'observation'), ('attendance', 'attendance'), ('fojt', 'fojt')], max_length=20),
        ),
    ]
