# Generated by Django 2.2.4 on 2020-06-28 14:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('businessGroup', '0002_auto_20200203_0831'),
        ('assessment', '0004_auto_20200628_1934'),
    ]

    operations = [
        migrations.CreateModel(
            name='CpcEvaluate',
            fields=[
                ('baseclass_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='businessGroup.BaseClass')),
                ('no_of_cpcs_attended', models.CharField(max_length=150)),
                ('score', models.DecimalField(decimal_places=2, default='0', max_digits=5)),
                ('cpbatch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cpc_batch', to='businessGroup.Batch')),
                ('trainee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cpc_trainee', to=settings.AUTH_USER_MODEL)),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cpc_trainer', to=settings.AUTH_USER_MODEL)),
            ],
            bases=('businessGroup.baseclass',),
        ),
    ]
