# Generated by Django 2.2.4 on 2020-06-28 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0005_cpcevaluate'),
    ]

    operations = [
        migrations.AddField(
            model_name='cpcevaluate',
            name='assessment_is',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cpc_assessment', to='assessment.BatchAssessment'),
        ),
    ]
