# Generated by Django 2.2.4 on 2020-06-30 11:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0006_cpcevaluate_assessment_is'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cpcevaluate',
            name='trainer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cpc_trainer', to=settings.AUTH_USER_MODEL),
        ),
    ]
