# Generated by Django 2.2.4 on 2020-08-14 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0007_auto_20200630_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batchassessment',
            name='status',
            field=models.CharField(choices=[('IN PROGRESS', 'in progress'), ('INITIATED', 'initiated'), ('APPROVED', 'approved'), ('PENDING', 'pending'), ('NOT APPROVED', 'not approved')], default='APPROVED', max_length=12),
        ),
    ]
