# Generated by Django 2.2.4 on 2020-08-15 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0008_auto_20200814_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batchassessment',
            name='status',
            field=models.CharField(choices=[('IN PROGRESS', 'in progress'), ('INITIATED', 'initiated'), ('APPROVED', 'approved'), ('PENDING', 'pending'), ('NOT APPROVED', 'not approved')], default='IN PROGRESS', max_length=12),
        ),
    ]
