# Generated by Django 2.2.4 on 2020-03-29 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0002_auto_20200203_0831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='file_status',
            field=models.CharField(choices=[('INITIATED', 'initiated'), ('APPROVED', 'approved'), ('PENDING', 'pending'), ('NOT APPROVED', 'not approved')], default='pending', max_length=15),
        ),
    ]
