# Generated by Django 2.2.4 on 2020-02-03 03:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('businessGroup', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessgroup',
            name='country_sales_manager',
            field=models.ForeignKey(limit_choices_to={'is_country_sales_manager': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='batch_csm', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='businessgroup',
            name='levels',
            field=models.ManyToManyField(related_name='bg', to='businessGroup.Level'),
        ),
        migrations.AddField(
            model_name='businessgroup',
            name='training_head',
            field=models.ForeignKey(limit_choices_to={'is_training_head': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='batch_head', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='batchmoduleactivation',
            name='batch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='batch_module', to='businessGroup.Batch'),
        ),
        migrations.AddField(
            model_name='batchmoduleactivation',
            name='module',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='module_active', to='businessGroup.Module'),
        ),
        migrations.AddField(
            model_name='batch',
            name='business_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='batch_group', to='businessGroup.BusinessGroup'),
        ),
        migrations.AddField(
            model_name='batch',
            name='course_trainer',
            field=models.ManyToManyField(limit_choices_to={'is_course_trainer': True}, related_name='tbatch_trainers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='batch',
            name='salesforce_trainer',
            field=models.ManyToManyField(limit_choices_to={'is_sfe_trainer': True}, related_name='sbatch_trainers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='batch',
            name='trainee',
            field=models.ManyToManyField(limit_choices_to={'is_trainee': True}, related_name='batch_trainees', to=settings.AUTH_USER_MODEL),
        ),
    ]
