# Generated by Django 2.2.4 on 2020-08-17 06:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businessGroup', '0004_auto_20200814_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='course_trainer',
            field=models.ManyToManyField(blank=True, limit_choices_to={'is_course_trainer': True}, related_name='tbatch_trainers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='batch',
            name='salesforce_trainer',
            field=models.ManyToManyField(blank=True, limit_choices_to={'is_sfe_trainer': True}, related_name='sbatch_trainers', to=settings.AUTH_USER_MODEL),
        ),
    ]
