# Generated by Django 2.2.4 on 2020-08-26 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businessGroup', '0005_auto_20200817_1148'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='refresher_course',
            field=models.BooleanField(default=False),
        ),
    ]
