# Generated by Django 2.2.4 on 2020-09-08 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businessGroup', '0006_batch_refresher_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
