# Generated by Django 2.2.4 on 2020-10-01 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businessGroup', '0007_auto_20200908_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessgroup',
            name='course_trainer_count',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='businessgroup',
            name='sfe_trainer_count',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
