# Generated by Django 2.2.4 on 2021-05-28 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('businessGroup', '0009_batch_batch_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessgroup',
            name='country_sales_manager',
        ),
    ]
