# Generated by Django 2.2.4 on 2021-05-29 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('businessGroup', '0010_remove_businessgroup_country_sales_manager'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batch',
            name='salesforce_trainer',
        ),
        migrations.RemoveField(
            model_name='businessgroup',
            name='levels',
        ),
        migrations.RemoveField(
            model_name='businessgroup',
            name='sfe_trainer_count',
        ),
    ]
