# Generated by Django 2.2.4 on 2021-05-29 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('businessGroup', '0011_auto_20210529_0845'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batchmoduleactivation',
            name='module',
        ),
    ]
