# Generated by Django 2.2.4 on 2021-05-29 13:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businessGroup', '0012_remove_batchmoduleactivation_module'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessgroup',
            name='course_trainer_count',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)]),
        ),
    ]
