# Generated by Django 3.2.4 on 2021-06-08 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businessGroup', '0013_auto_20210529_1838'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
