# Generated by Django 2.2.4 on 2020-05-08 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('businessGroup', '0002_auto_20200203_0831'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answerfeed',
            name='batch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='batch_feed', to='businessGroup.Batch'),
        ),
    ]
