# Generated by Django 2.2.4 on 2020-10-05 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_answerfeed_batch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lmsuser',
            name='mobile_number',
            field=models.CharField(max_length=15),
        ),
    ]
