# Generated by Django 3.2.4 on 2021-06-08 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20201008_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lmsuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
    ]
