# Generated by Django 2.2.4 on 2020-04-08 07:37

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_auto_20200402_2027'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailnotifications',
            name='required_data',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
    ]
