# Generated by Django 3.2.4 on 2021-06-08 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_auto_20201008_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtemplates',
            name='model',
            field=models.CharField(choices=[('USER', 'user'), ('MODULE', 'module'), ('LEVEL', 'level'), ('BUSINESSGROUP', 'businessgroup'), ('BATCH', 'batch'), ('ASSESSMENT', 'assessment'), ('BATCHASSESSMENT', 'batchassessment'), ('ANSWER', 'answer'), ('FEEDBACK', 'feedback'), ('ATTENDANCE', 'attendance'), ('MATERIAL', 'material'), ('FIELDSTUDY', 'fieldstudy')], max_length=15),
        ),
    ]
